{% set name = "ipygany" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1690ad0da54942954b9139c05076360f3c99f171d35c81913ba62f98c677e26b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - nodejs
  run:
    - ipywidgets >=7.5.0
    - python >=3.5
    - traittypes
    - numpy

test:
  imports:
    - ipygany

about:
  home: https://github.com/QuantStack/ipygany
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 3-D Scientific Visualization in Jupyter

extra:
  recipe-maintainers:
    - martinRenou
    - JohanMabille
    - SylvainCorlay
    - wolfv
    - davidbrochart
